[2017-07-21 00:10:39]: runtime-log INFO 21 【获取微信全局唯一票据access_token】>>>执行定时器任务
[I 170721 00:10:39 wxschedule:21] 【获取微信全局唯一票据access_token】>>>执行定时器任务
[2017-07-21 00:10:39]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 00:10:39 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 00:10:39]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN","expires_in":7200}
[I 170721 00:10:39 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN","expires_in":7200}
[2017-07-21 00:10:39]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 00:10:39 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 00:10:39]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP_GnvHgifOac2sA6ja5XnNQrnwz451DB684Drr8b_1Zqw","expires_in":7200}
[I 170721 00:10:39 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP_GnvHgifOac2sA6ja5XnNQrnwz451DB684Drr8b_1Zqw","expires_in":7200}
[2017-07-21 00:10:40]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 00:10:40 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 00:10:40]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"64d4bdde8bfc327668e4d0d8f81d48fd0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 00:10:40 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"64d4bdde8bfc327668e4d0d8f81d48fd0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[2017-07-21 00:11:24]: runtime-log INFO 188 name is张斌辉
[I 170721 00:11:24 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:11:24 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567084.5351431, 'msecs': 535.1431369781494, 'relativeCreated': 45003.04293632507, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:11:24]: runtime-log INFO 214 {"type":"image","media_id":"INph457qFScc_GT37GfslEfus20H9aWSEqwj-G3yzwTBGPveaYcaxMG3xRxvSZVP","created_at":1500567084}
[I 170721 00:11:24 wxauthorize:214] {"type":"image","media_id":"INph457qFScc_GT37GfslEfus20H9aWSEqwj-G3yzwTBGPveaYcaxMG3xRxvSZVP","created_at":1500567084}
[I 170721 00:11:24 web:2063] 200 POST /wxsignature?signature=55beeed412742ce879dace24353bf72f655225d0&timestamp=1500567083&nonce=723884140&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.157) 833.75ms
[2017-07-21 00:11:27]: runtime-log INFO 188 name is张斌辉
[I 170721 00:11:27 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:11:27 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567087.1457605, 'msecs': 145.76053619384766, 'relativeCreated': 47613.66033554077, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:11:27]: runtime-log INFO 214 {"type":"image","media_id":"hfccWCroRUMd4OJCEpb3Uo8_h67pSF_1p3Qn8lEs6t3DbUg0OKyhqOPsFwQJOiWM","created_at":1500567087}
[I 170721 00:11:27 wxauthorize:214] {"type":"image","media_id":"hfccWCroRUMd4OJCEpb3Uo8_h67pSF_1p3Qn8lEs6t3DbUg0OKyhqOPsFwQJOiWM","created_at":1500567087}
[I 170721 00:11:27 web:2063] 200 POST /wxsignature?signature=e14591e04ef098e629ed0c46f248a51278f8d21a&timestamp=1500567086&nonce=991637684&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 598.03ms
[2017-07-21 00:14:06]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:06 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:06 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567246.1128504, 'msecs': 112.85042762756348, 'relativeCreated': 206580.7502269745, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:06]: runtime-log INFO 214 {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPgGJ6r9l5WRVmy4JBeA9cCMcXXmaILds8gbpddWb4wE6","created_at":1500567246}
[I 170721 00:14:06 wxauthorize:214] {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPgGJ6r9l5WRVmy4JBeA9cCMcXXmaILds8gbpddWb4wE6","created_at":1500567246}
[I 170721 00:14:06 web:2063] 200 POST /wxsignature?signature=efe5fa094a253ae2e388840cff34412b5acbc16a&timestamp=1500567245&nonce=1519411270&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 590.73ms
[2017-07-21 00:14:08]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:08 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:08 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567248.8771453, 'msecs': 877.1452903747559, 'relativeCreated': 209345.04508972168, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:08]: runtime-log INFO 214 {"type":"image","media_id":"aZwe3uUT77l3lvOmGTZUJX7EMPJ49W3SSzNOTWYtnLi3jIFKoSm5c5hjcuD_kAGu","created_at":1500567248}
[I 170721 00:14:08 wxauthorize:214] {"type":"image","media_id":"aZwe3uUT77l3lvOmGTZUJX7EMPJ49W3SSzNOTWYtnLi3jIFKoSm5c5hjcuD_kAGu","created_at":1500567248}
[I 170721 00:14:08 web:2063] 200 POST /wxsignature?signature=80c8512959449f691886873833feaf70c186f0b4&timestamp=1500567248&nonce=1797280239&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 551.09ms
[2017-07-21 00:14:12]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:12 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:12 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567252.1843123, 'msecs': 184.3123435974121, 'relativeCreated': 212652.21214294434, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:12]: runtime-log INFO 214 {"type":"image","media_id":"IX-7tNO-2u-yuuC4fDQyKTl7WqXg20-qvBg49jaRBlfFJD2YeHbKBsTLwPllk5F6","created_at":1500567252}
[I 170721 00:14:12 wxauthorize:214] {"type":"image","media_id":"IX-7tNO-2u-yuuC4fDQyKTl7WqXg20-qvBg49jaRBlfFJD2YeHbKBsTLwPllk5F6","created_at":1500567252}
[I 170721 00:14:12 web:2063] 200 POST /wxsignature?signature=e02bbd14104dbe4695b8f3d3a1b244acfb858973&timestamp=1500567251&nonce=1313936936&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 570.68ms
[I 170721 00:14:12 web:2063] 200 POST /wxsignature?signature=85696f72404a688ea2b328a026727c513af86522&timestamp=1500567252&nonce=52766694&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 0.88ms
[2017-07-21 00:14:12]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:12 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:12 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567252.3184903, 'msecs': 318.49026679992676, 'relativeCreated': 212786.39006614685, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:12]: runtime-log INFO 214 {"type":"image","media_id":"2gIkxdtP9d11_43hZnuEE899PYq5Yj-im2Zy1mq-yfWyjwHuRt8QVASCXgJdRCr7","created_at":1500567252}
[I 170721 00:14:12 wxauthorize:214] {"type":"image","media_id":"2gIkxdtP9d11_43hZnuEE899PYq5Yj-im2Zy1mq-yfWyjwHuRt8QVASCXgJdRCr7","created_at":1500567252}
[I 170721 00:14:12 web:2063] 200 POST /wxsignature?signature=6a088de3db73a0d1e9c4c077fc59d17dcfbbfbce&timestamp=1500567251&nonce=934189151&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 694.51ms
[I 170721 00:14:12 web:2063] 200 POST /wxsignature?signature=b059872a138b8525c7407a934d897037556bf897&timestamp=1500567252&nonce=169965738&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.157) 0.67ms
[2017-07-21 00:14:13]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:13 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:13 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567253.3516989, 'msecs': 351.6988754272461, 'relativeCreated': 213819.59867477417, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:13]: runtime-log INFO 214 {"type":"image","media_id":"D1Y6_fo5ERZL4ehNDR_mXI7xbC_6ogFVnm1vi2BClo2p1dUFL7tiBX1gaOcqrwve","created_at":1500567253}
[I 170721 00:14:13 wxauthorize:214] {"type":"image","media_id":"D1Y6_fo5ERZL4ehNDR_mXI7xbC_6ogFVnm1vi2BClo2p1dUFL7tiBX1gaOcqrwve","created_at":1500567253}
[I 170721 00:14:13 web:2063] 200 POST /wxsignature?signature=e3a9d194751b39aebef89b4bf7e08586d370f2c9&timestamp=1500567252&nonce=1954475974&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 520.95ms
[2017-07-21 00:14:13]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:13 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:13 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567253.5401182, 'msecs': 540.1182174682617, 'relativeCreated': 214008.0180168152, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:13]: runtime-log INFO 214 {"type":"image","media_id":"kywauZ86RbPq9-eF6nDwYIn4tSO1D2qjJRYXNVtpc7l2XuSjs2GK5aJxGGE5brFZ","created_at":1500567253}
[I 170721 00:14:13 wxauthorize:214] {"type":"image","media_id":"kywauZ86RbPq9-eF6nDwYIn4tSO1D2qjJRYXNVtpc7l2XuSjs2GK5aJxGGE5brFZ","created_at":1500567253}
[I 170721 00:14:13 web:2063] 200 POST /wxsignature?signature=40b1e6a38ecb9eb5b6dba399f591846508ef714f&timestamp=1500567253&nonce=212969781&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 524.90ms
[2017-07-21 00:14:14]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:14 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:14 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567254.3007126, 'msecs': 300.71258544921875, 'relativeCreated': 214768.61238479614, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:14]: runtime-log INFO 214 {"type":"image","media_id":"2gIkxdtP9d11_43hZnuEExrpmOmV_f_u86UiPKiWMbZhko4GLz6lGRMfuuO_eM_8","created_at":1500567254}
[I 170721 00:14:14 wxauthorize:214] {"type":"image","media_id":"2gIkxdtP9d11_43hZnuEExrpmOmV_f_u86UiPKiWMbZhko4GLz6lGRMfuuO_eM_8","created_at":1500567254}
[I 170721 00:14:14 web:2063] 200 POST /wxsignature?signature=14ec7b6074eb86d913fb039c034eaf3188fbeb9d&timestamp=1500567253&nonce=461220647&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 582.81ms
[2017-07-21 00:14:14]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:14 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:14 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567254.529479, 'msecs': 529.4790267944336, 'relativeCreated': 214997.37882614136, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:14]: runtime-log INFO 214 {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPlUpVLDku9i_8mNettzc2oVv6otagqEUQYbs_F-1CE8U","created_at":1500567254}
[I 170721 00:14:14 wxauthorize:214] {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPlUpVLDku9i_8mNettzc2oVv6otagqEUQYbs_F-1CE8U","created_at":1500567254}
[I 170721 00:14:14 web:2063] 200 POST /wxsignature?signature=2397626cc637061bcdae30ff8810189b4f45ed6d&timestamp=1500567253&nonce=914744904&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 604.53ms
[2017-07-21 00:14:14]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:14 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:14 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567254.869076, 'msecs': 869.0760135650635, 'relativeCreated': 215336.975812912, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:14]: runtime-log INFO 214 {"type":"image","media_id":"N8QI9MHgkjsDXGeVI7KPLlQhWimpWu-z2k836fT48Wy1MNghz4bROLjunTFdXaGM","created_at":1500567254}
[I 170721 00:14:14 wxauthorize:214] {"type":"image","media_id":"N8QI9MHgkjsDXGeVI7KPLlQhWimpWu-z2k836fT48Wy1MNghz4bROLjunTFdXaGM","created_at":1500567254}
[I 170721 00:14:14 web:2063] 200 POST /wxsignature?signature=31b747a886aea56e4f2549bf786bf6ea502d6de8&timestamp=1500567254&nonce=1949164423&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 544.37ms
[I 170721 00:14:17 web:2063] 200 POST /wxsignature?signature=e0c6aeeb81046f623959ce25fffc92a5cb1d9721&timestamp=1500567257&nonce=2139168767&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 0.99ms
[I 170721 00:14:17 web:2063] 200 POST /wxsignature?signature=684dca6b3558b03e2997ece8e3297a16a9b3c49c&timestamp=1500567257&nonce=607075663&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 0.85ms
[I 170721 00:14:17 web:2063] 200 POST /wxsignature?signature=d901a32e2fa4cbd2dac4f07e0566e608bc942edf&timestamp=1500567257&nonce=1135210661&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 0.76ms
[2017-07-21 00:14:19]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:19 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:19 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567259.2748294, 'msecs': 274.8293876647949, 'relativeCreated': 219742.72918701172, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:19]: runtime-log INFO 214 {"type":"image","media_id":"0BVCQH9LPOnXnPobyUAxv2o7dkmgr8jpC4BEpBdGtBEJaGLRCe2yeOGTsDU7xO5z","created_at":1500567259}
[I 170721 00:14:19 wxauthorize:214] {"type":"image","media_id":"0BVCQH9LPOnXnPobyUAxv2o7dkmgr8jpC4BEpBdGtBEJaGLRCe2yeOGTsDU7xO5z","created_at":1500567259}
[I 170721 00:14:19 web:2063] 200 POST /wxsignature?signature=832901c3df21c1e3b3b8f957d5117873afd7b7e4&timestamp=1500567258&nonce=1464425454&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 517.81ms
[2017-07-21 00:14:22]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:22 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:22 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567262.011877, 'msecs': 11.877059936523438, 'relativeCreated': 222479.77685928345, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:22]: runtime-log INFO 214 {"type":"image","media_id":"N8QI9MHgkjsDXGeVI7KPLnUUE0oRl0fgP4zzA1t0zuoqctuhoGW_z_KophqOIFEw","created_at":1500567262}
[I 170721 00:14:22 wxauthorize:214] {"type":"image","media_id":"N8QI9MHgkjsDXGeVI7KPLnUUE0oRl0fgP4zzA1t0zuoqctuhoGW_z_KophqOIFEw","created_at":1500567262}
[I 170721 00:14:22 web:2063] 200 POST /wxsignature?signature=c2d5335d224045bda8fb715bf87f404cc9998b35&timestamp=1500567261&nonce=2128154651&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 531.34ms
[2017-07-21 00:14:22]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:22 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:22 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567262.22442, 'msecs': 224.42007064819336, 'relativeCreated': 222692.31986999512, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:22]: runtime-log INFO 214 {"type":"image","media_id":"kywauZ86RbPq9-eF6nDwYG36RytjsKWnXpYKOSg-O8Q2jz8k0tUxTOdgsD3a4_C1","created_at":1500567262}
[I 170721 00:14:22 wxauthorize:214] {"type":"image","media_id":"kywauZ86RbPq9-eF6nDwYG36RytjsKWnXpYKOSg-O8Q2jz8k0tUxTOdgsD3a4_C1","created_at":1500567262}
[I 170721 00:14:22 web:2063] 200 POST /wxsignature?signature=6d39ecb440f40071b83b842dedf040f33456001b&timestamp=1500567261&nonce=135221727&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.152) 524.92ms
[2017-07-21 00:14:22]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:22 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:22 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567262.3162818, 'msecs': 316.281795501709, 'relativeCreated': 222784.18159484863, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:22]: runtime-log INFO 214 {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPoStZZcUFDrSJgLaLUbBwbVggYi6vTe9xGAplZV8a17A","created_at":1500567262}
[I 170721 00:14:22 wxauthorize:214] {"type":"image","media_id":"33DGtqC28dOIgXh8nenJPoStZZcUFDrSJgLaLUbBwbVggYi6vTe9xGAplZV8a17A","created_at":1500567262}
[I 170721 00:14:22 web:2063] 200 POST /wxsignature?signature=87b33dba2b19dde03562bdda2f6f3f53427b8e84&timestamp=1500567261&nonce=1062999483&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 619.36ms
[2017-07-21 00:14:22]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:22 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:22 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567262.424732, 'msecs': 424.731969833374, 'relativeCreated': 222892.6317691803, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:22]: runtime-log INFO 214 {"type":"image","media_id":"INph457qFScc_GT37GfslDprYnnGoCsCIQvc8eq4b89ZdHXaxlb5QE7sM3PDQ_to","created_at":1500567262}
[I 170721 00:14:22 wxauthorize:214] {"type":"image","media_id":"INph457qFScc_GT37GfslDprYnnGoCsCIQvc8eq4b89ZdHXaxlb5QE7sM3PDQ_to","created_at":1500567262}
[I 170721 00:14:22 web:2063] 200 POST /wxsignature?signature=5c01ecfff67e2a906ab8dc7dac6b0ed7d4f49f48&timestamp=1500567261&nonce=1050214699&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.157) 663.72ms
[2017-07-21 00:14:25]: runtime-log INFO 188 name is张斌辉
[I 170721 00:14:25 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:14:25 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500567265.0493705, 'msecs': 49.370527267456055, 'relativeCreated': 225517.27032661438, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:14:25]: runtime-log INFO 214 {"type":"image","media_id":"KQyjCaQW3mqkAIH8jPplGhtmD7-9FKhd2cTuca1TBI_9ClvDw-rkh_hQWz1jl3o2","created_at":1500567265}
[I 170721 00:14:25 wxauthorize:214] {"type":"image","media_id":"KQyjCaQW3mqkAIH8jPplGhtmD7-9FKhd2cTuca1TBI_9ClvDw-rkh_hQWz1jl3o2","created_at":1500567265}
[I 170721 00:14:25 web:2063] 200 POST /wxsignature?signature=4c085154956d064daf8733af94d7417b0dd69844&timestamp=1500567264&nonce=1846710456&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.147) 531.84ms
[2017-07-21 00:57:09]: runtime-log INFO 188 name is张斌辉
[I 170721 00:57:09 wxauthorize:188] name is张斌辉
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 36, in <module>
    main()
  File "run.py", line 31, in main
    tornado.ioloop.IOLoop.current().start()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/FilmHub-Tornado/core/server/wxauthorize.py", line 198, in on_response
    logger.info("access_token is", token)
Message: 'access_token is'
Arguments: ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',)
[I 170721 00:57:09 wxauthorize:198] Bad message (TypeError('not all arguments converted during string formatting',)): {'name': 'runtime-log', 'msg': 'access_token is', 'args': ('88fJJgkriOWphbw7GVbKOI8uDcLVe_AR_EdpJNz7D31Ao1BKEJFvoR_zulq31icqDBdW-m6TFSYjgfLpJOS-Bj0Bm96zDN5EjO7HdceiMD97Sgiwlyhw-br0J-v4MxuPJWZgADAXKN',), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/root/FilmHub-Tornado/core/server/wxauthorize.py', 'filename': 'wxauthorize.py', 'module': 'wxauthorize', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 198, 'funcName': 'on_response', 'created': 1500569829.5333555, 'msecs': 533.3554744720459, 'relativeCreated': 2790001.255273819, 'thread': 140164942583616, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30309}
[2017-07-21 00:57:09]: runtime-log INFO 214 {"type":"image","media_id":"xAHI7sZ-jJTZFFxpPNtqW7gQNiYUGMqgNfkQXcwlXeYS7ct6v7v5H50Iia5FsUxV","created_at":1500569829}
[I 170721 00:57:09 wxauthorize:214] {"type":"image","media_id":"xAHI7sZ-jJTZFFxpPNtqW7gQNiYUGMqgNfkQXcwlXeYS7ct6v7v5H50Iia5FsUxV","created_at":1500569829}
[I 170721 00:57:09 web:2063] 200 POST /wxsignature?signature=943d2d07f4e9761887985b305902e40e6fd1ce1a&timestamp=1500569828&nonce=1300651161&openid=oamMDw0uP9G73IsqrE5O4jOr_Yqk (182.254.86.142) 929.86ms
[W 170721 01:26:38 web:2063] 404 GET /phpmyadmin (221.131.28.100) 95.40ms
[2017-07-21 02:07:20]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 02:07:20 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 02:07:20]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"BJN6EtsGwHU7XswKwVYwM4jpDmrPDQJsghTn-2jDfmqckiVCD3nDtPqvJO0AsdCNg2zfTDCRwEpCdUVnPbA81s2AdGqPY00RzGOAY3IzZjJ6jmAkwpcCAFf9zP39L71QTKIgAFAKBZ","expires_in":7200}
[I 170721 02:07:20 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"BJN6EtsGwHU7XswKwVYwM4jpDmrPDQJsghTn-2jDfmqckiVCD3nDtPqvJO0AsdCNg2zfTDCRwEpCdUVnPbA81s2AdGqPY00RzGOAY3IzZjJ6jmAkwpcCAFf9zP39L71QTKIgAFAKBZ","expires_in":7200}
[2017-07-21 02:07:20]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 02:07:20 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 02:07:20]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8F8LoYczyvHa3OkhnHUbrbX2tH8_ZbU3OrzZnI5MCqOQ","expires_in":7200}
[I 170721 02:07:20 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8F8LoYczyvHa3OkhnHUbrbX2tH8_ZbU3OrzZnI5MCqOQ","expires_in":7200}
[2017-07-21 02:07:20]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 02:07:20 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 02:07:20]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"c601e936cff8321260f7eb23ab7e82fa0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 02:07:20 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"c601e936cff8321260f7eb23ab7e82fa0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[W 170721 02:28:43 web:2063] 404 GET / (47.93.90.175) 0.73ms
[W 170721 02:30:40 web:2063] 404 GET http://www.qq.com/404/search_children.js (120.132.3.151) 0.86ms
[2017-07-21 04:04:00]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 04:04:00 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 04:04:01]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"4yE-wpsUFDJHpawG8HSfQ4lsBNYPOvnQNHC651gwyxulYN8sOzNmR8dECGmqGF2mQfBnaVhd-vYtYXYb9JwpLOf7oYhIWYrf3F7H9JfqypBnX53vOEehgm4WxDN9MxxEWNYaAJAJAL","expires_in":7200}
[I 170721 04:04:01 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"4yE-wpsUFDJHpawG8HSfQ4lsBNYPOvnQNHC651gwyxulYN8sOzNmR8dECGmqGF2mQfBnaVhd-vYtYXYb9JwpLOf7oYhIWYrf3F7H9JfqypBnX53vOEehgm4WxDN9MxxEWNYaAJAJAL","expires_in":7200}
[2017-07-21 04:04:01]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 04:04:01 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 04:04:01]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8SEIZbZrSpy4A10pqkJkBqLkjBFhe5gVX_9SPBULfC_g","expires_in":7200}
[I 170721 04:04:01 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8SEIZbZrSpy4A10pqkJkBqLkjBFhe5gVX_9SPBULfC_g","expires_in":7200}
[2017-07-21 04:04:01]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 04:04:01 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 04:04:01]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"f35531e6b5fe498b176a7bdeca74454b0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 04:04:01 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"f35531e6b5fe498b176a7bdeca74454b0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[2017-07-21 06:00:39]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 06:00:39 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 06:00:39]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"dk0G8TBagY25nD7xCMJYFBMqlZx28HDk57cf2MbXpEstYFigHfN_DI2dDFqmKMS6OJP8eANPL9ejmJrL9hySxiJkj91lsDg48mUrUL7Ypez5_WvSSvQ9P8DCo_nNrIeUQYZbAGABJK","expires_in":7200}
[I 170721 06:00:39 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"dk0G8TBagY25nD7xCMJYFBMqlZx28HDk57cf2MbXpEstYFigHfN_DI2dDFqmKMS6OJP8eANPL9ejmJrL9hySxiJkj91lsDg48mUrUL7Ypez5_WvSSvQ9P8DCo_nNrIeUQYZbAGABJK","expires_in":7200}
[2017-07-21 06:00:40]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 06:00:40 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 06:00:40]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9nrwPNET2yvTd7WhUTY-edvg_SofK9jMr9nyVtByPd1A","expires_in":7200}
[I 170721 06:00:40 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9nrwPNET2yvTd7WhUTY-edvg_SofK9jMr9nyVtByPd1A","expires_in":7200}
[2017-07-21 06:00:40]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 06:00:40 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 06:00:40]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"0e7a1eb6f2eeab380f2b526a95aadb2e0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 06:00:40 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"0e7a1eb6f2eeab380f2b526a95aadb2e0007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[W 170721 06:49:04 web:2063] 404 GET / (183.61.47.108) 109.06ms
[W 170721 06:49:04 web:2063] 404 OPTIONS / (183.61.47.108) 0.82ms
[I 170721 06:49:04 http1connection:253] Malformed HTTP message from 183.61.47.108: Malformed HTTP version in HTTP Request-Line: 'RTSP/1.0'
[W 170721 06:49:09 web:2063] 404 GET /nice%20ports%2C/Tri%6Eity.txt%2ebak (183.61.47.108) 0.91ms
[I 170721 06:49:14 http1connection:253] Malformed HTTP message from 183.61.47.108: Malformed HTTP request line
[W 170721 06:50:28 web:2063] 404 GET http://www.baidu.com/cache/global/img/gs.gif (172.82.166.210) 0.69ms
[2017-07-21 07:57:19]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 07:57:19 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 07:57:19]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"xeEGYt8HdUSLc3SaeggMaED-LHv5eF6nEc0vky704aKbOZPSnwYvOr9XFdZ4DtZwot17Lepn484m4hEAQyrv9qhQ8ut7pBe43HuJbF49WPRlFAxqEZb_9Ghwxf_Ydp_XLZUjAFARFA","expires_in":7200}
[I 170721 07:57:19 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"xeEGYt8HdUSLc3SaeggMaED-LHv5eF6nEc0vky704aKbOZPSnwYvOr9XFdZ4DtZwot17Lepn484m4hEAQyrv9qhQ8ut7pBe43HuJbF49WPRlFAxqEZb_9Ghwxf_Ydp_XLZUjAFARFA","expires_in":7200}
[2017-07-21 07:57:19]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 07:57:19 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 07:57:19]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9nrwPNET2yvTd7WhUTY-edvg_SofK9jMr9nyVtByPd1A","expires_in":7200}
[I 170721 07:57:19 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9nrwPNET2yvTd7WhUTY-edvg_SofK9jMr9nyVtByPd1A","expires_in":7200}
[2017-07-21 07:57:20]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 07:57:20 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 07:57:20]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"7be7dbae150a1bcb2cbe2456f10dfd110007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 07:57:20 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"7be7dbae150a1bcb2cbe2456f10dfd110007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[2017-07-21 09:53:59]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 09:53:59 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 09:53:59]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"56mcWt5P3oyo9Jb-SfeRRV8WjnO5au6w48ufEFYgO5lRTl9wqP-rGKoMnvuLwG4FM8nHeSHLgz1nXJ7-_vcxH-tQ6Qp7C66aOppqtp00JW3rCaCIvAVH6M88szLY4kdkADDcACARUU","expires_in":7200}
[I 170721 09:53:59 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"56mcWt5P3oyo9Jb-SfeRRV8WjnO5au6w48ufEFYgO5lRTl9wqP-rGKoMnvuLwG4FM8nHeSHLgz1nXJ7-_vcxH-tQ6Qp7C66aOppqtp00JW3rCaCIvAVH6M88szLY4kdkADDcACARUU","expires_in":7200}
[2017-07-21 09:53:59]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 09:53:59 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 09:53:59]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8dXgBYcrcbukjaFcNAfG6083MRRQt-sfi0U7eeVjl01g","expires_in":7200}
[I 170721 09:53:59 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP8dXgBYcrcbukjaFcNAfG6083MRRQt-sfi0U7eeVjl01g","expires_in":7200}
[2017-07-21 09:54:00]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 09:54:00 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 09:54:00]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"ccd0678c20a5bbb89740ebff147852000007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 09:54:00 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"ccd0678c20a5bbb89740ebff147852000007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[W 170721 10:28:31 web:2063] 404 GET http://www.baidu.com/cache/global/img/gs.gif (80.82.78.38) 0.86ms
[W 170721 10:35:32 web:2063] 404 GET / (59.110.6.177) 0.87ms
[W 170721 11:07:16 web:2063] 404 GET / (183.61.47.108) 0.68ms
[W 170721 11:07:16 web:2063] 404 OPTIONS / (183.61.47.108) 0.79ms
[I 170721 11:07:16 http1connection:253] Malformed HTTP message from 183.61.47.108: Malformed HTTP version in HTTP Request-Line: 'RTSP/1.0'
[W 170721 11:07:21 web:2063] 404 GET /nice%20ports%2C/Tri%6Eity.txt%2ebak (183.61.47.108) 0.85ms
[I 170721 11:07:26 http1connection:253] Malformed HTTP message from 183.61.47.108: Malformed HTTP request line
[2017-07-21 11:50:39]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 11:50:39 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 11:50:39]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"ggzGDRSxWJB1RxGrCCsmreMjwpiPK8kpejKAk0YF8GWadQxdsvVe4HErgOAFXsTfieBYXqbfKIbCb11Rdc2NCSDRqlgEK2AnvXA6DXB0ZrUAi25efCyZUvby3DkqLYw2VMQgADAQHL","expires_in":7200}
[I 170721 11:50:39 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"ggzGDRSxWJB1RxGrCCsmreMjwpiPK8kpejKAk0YF8GWadQxdsvVe4HErgOAFXsTfieBYXqbfKIbCb11Rdc2NCSDRqlgEK2AnvXA6DXB0ZrUAi25efCyZUvby3DkqLYw2VMQgADAQHL","expires_in":7200}
[2017-07-21 11:50:39]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 11:50:39 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 11:50:39]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9_l0lcKRSwlSmXcHHxofD1Tu4fyNrIbB9OD1uWPkTRHg","expires_in":7200}
[I 170721 11:50:39 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP9_l0lcKRSwlSmXcHHxofD1Tu4fyNrIbB9OD1uWPkTRHg","expires_in":7200}
[2017-07-21 11:50:40]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 11:50:40 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 11:50:40]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"eb4ca8d8185f3a8d6fc270f70c5524f10007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 11:50:40 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"eb4ca8d8185f3a8d6fc270f70c5524f10007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 12:43:27 web:2063] 200 POST /wxsignature?signature=7019686f38fa0fbc2bb6406d2154c5551492a519&timestamp=1500612207&nonce=1170656915&openid=oamMDw4aE9xf-pW_r_cn9AAedtIw (182.254.86.156) 179.62ms
[I 170721 12:43:54 web:2063] 200 POST /wxsignature?signature=a386988f632ac35efb90107219b4cbe4a31a9b25&timestamp=1500612234&nonce=679115751&openid=oamMDw4aE9xf-pW_r_cn9AAedtIw (182.254.86.146) 1.30ms
[W 170721 13:10:15 web:2063] 404 GET / (118.190.79.161) 1.10ms
[2017-07-21 13:47:19]: runtime-log INFO 31 【获取微信全局唯一票据access_token】Response[200]
[I 170721 13:47:19 wxschedule:31] 【获取微信全局唯一票据access_token】Response[200]
[2017-07-21 13:47:19]: runtime-log INFO 34 【获取微信全局唯一票据access_token】>>>{"access_token":"fPqV64lXDsd3_wnW1tfPxjqmUSgjIGMVh1WjT3qrvRE3iz3y0LgWHMbK3NGZ9lz6fhbLASIvuZZb3Kd6YhwouVQ15l2ldQfwp6o1wgW0hMEDNRdAGAQAE","expires_in":7200}
[I 170721 13:47:19 wxschedule:34] 【获取微信全局唯一票据access_token】>>>{"access_token":"fPqV64lXDsd3_wnW1tfPxjqmUSgjIGMVh1WjT3qrvRE3iz3y0LgWHMbK3NGZ9lz6fhbLASIvuZZb3Kd6YhwouVQ15l2ldQfwp6o1wgW0hMEDNRdAGAQAE","expires_in":7200}
[2017-07-21 13:47:19]: runtime-log INFO 77 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[I 170721 13:47:19 wxschedule:77] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket的Response[200]
[2017-07-21 13:47:19]: runtime-log INFO 80 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP-zPv7Yr8moLbexTDAqyvfz45mkgbG2YyFdTT-MBDFm9A","expires_in":7200}
[I 170721 13:47:19 wxschedule:80] 【微信JS-SDK】获取JS_SDK权限签名的jsapi_ticket>>>>{"errcode":0,"errmsg":"ok","ticket":"kgt8ON7yVITDhtdwci0qedSPgAqfQ2yPqcXm-y8PiP-zPv7Yr8moLbexTDAqyvfz45mkgbG2YyFdTT-MBDFm9A","expires_in":7200}
[2017-07-21 13:47:20]: runtime-log INFO 56 【获取微店全局唯一票据access_token】Response[200]
[I 170721 13:47:20 wxschedule:56] 【获取微店全局唯一票据access_token】Response[200]
[2017-07-21 13:47:20]: runtime-log INFO 59 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"53cd9dff523364cfd3b329f0bc629c090007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
[I 170721 13:47:20 wxschedule:59] 【获取微店全局唯一票据access_token】>>>{"result":{"access_token":"53cd9dff523364cfd3b329f0bc629c090007451073","expire_in":90000},"status":{"status_code":0,"status_reason":"success"}}
